# Generated by Django 3.1.5 on 2021-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
