# Generated by Django 3.1.5 on 2021-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20210313_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='serving',
            field=models.CharField(default='1 Dish', max_length=100),
            preserve_default=False,
        ),
    ]
