# Generated by Django 3.1.5 on 2021-03-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_dish_serving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='dish',
            name='cooktime',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='dish',
            name='onhandqty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='status',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
