# Generated by Django 3.1.5 on 2021-04-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0014_auto_20210403_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='type',
        ),
    ]
