# Generated by Django 3.1.5 on 2021-04-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0015_remove_dish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
