# Generated by Django 3.1.5 on 2021-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0021_auto_20210417_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
