# Generated by Django 3.1.5 on 2021-04-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0022_auto_20210417_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='cooked',
        ),
    ]
