# Generated by Django 3.1.5 on 2021-05-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0024_order_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cooked',
            new_name='completed',
        ),
    ]
