# Generated by Django 3.1.5 on 2021-05-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0026_order_confirmdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
    ]
