# Generated by Django 3.1.5 on 2021-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0027_order_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
