# Generated by Django 3.1.5 on 2021-05-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0028_auto_20210512_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='open',
        ),
    ]
