# Generated by Django 3.1.5 on 2021-05-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0029_auto_20210514_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
